### ISSUE TITLE
Positive issue

### ISSUE THREAD

**Issue by RachBLondon** [HMS-FAC/FirstCruise#7]
Nice readme :-)

**Comment by RachBLondon** [comment]
Sorry spoke to soon, getting errors when I start the dev:build

ERROR in ./~/react-leaflet/lib/index.js
Module not found: Error: Cannot resolve module 'leaflet' in /Users/rachelblack/Dropbox/FAC6/w9/FirstCruise/node_modules/react-leaflet/lib
 @ ./~/react-leaflet/lib/index.js 11:15-33

**Comment by hdrdavies** [comment]
@RachBLondon did you npm install and run build first?

**Comment by tormod17** [comment]
Okay - we haven't saved 'leaflet' as a dependency. I have updated the package JSON but if you 'npm install leaflet'  it will fix. Close when you can cheers !!

**Comment by RachBLondon** [comment]
npm intstall is working now but the image is quite small when I visit the site 
![screen shot 2015-11-16 at 15 49 21](https://cloud.githubusercontent.com/assets/8742251/11186466/bd8939c4-8c79-11e5-8de5-a322803e78d8.png)

**Comment by hdrdavies** [comment]
that's just how it is at the moment @RachBLondon

**Comment by hdrdavies** [comment]
made it bigger :sparkles:

**Comment by RachBLondon** [comment]
Cool Cool.
